swagger: "2.0"
info:
  title: Demo Title
  description: Tell me more
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /ask:
    get:
      operationId: aGetFunction
      produces:
        - application/json
      x-google-backend:
        address: ${get_function_url}
      responses:
        "200":
          description: Let me tell you more
  /tell:
    put:
      operationId: aPutFunction
      produces:
        - application/json
      x-google-backend:
        address: ${put_function_url}
      responses:
        "201":
          description: Got it
  
