name: Terraform checks and linting

on: [push]

jobs:
  terraform-lint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Terraform Action from oak-terraform-actions
        uses: oaknational/oak-terraform-actions/actions/terraform-checks@f9d60cde94c5e32f7c0537e3ec2207c9112d0941 # v1.13.0
        with:
          terraform_base_dir: modules
